// Generated by scripts/assign-demo-portraits.cjs from src/shared/people/portraitPool.json. Do not edit.
// Metro needs literal require() paths: 1080×1080 HD portraits and 256×256 thumbnails.
export const portraitImages: Record<string, { hd: number; thumb: number }> = {
  "in-m-01": {
    hd: require("../../../assets/profiles/people/in-m-01.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-01.jpg"),
  },
  "in-m-02": {
    hd: require("../../../assets/profiles/people/in-m-02.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-02.jpg"),
  },
  "in-m-03": {
    hd: require("../../../assets/profiles/people/in-m-03.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-03.jpg"),
  },
  "in-m-04": {
    hd: require("../../../assets/profiles/people/in-m-04.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-04.jpg"),
  },
  "in-m-05": {
    hd: require("../../../assets/profiles/people/in-m-05.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-05.jpg"),
  },
  "in-m-06": {
    hd: require("../../../assets/profiles/people/in-m-06.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-06.jpg"),
  },
  "in-m-07": {
    hd: require("../../../assets/profiles/people/in-m-07.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-07.jpg"),
  },
  "in-m-08": {
    hd: require("../../../assets/profiles/people/in-m-08.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-08.jpg"),
  },
  "in-m-09": {
    hd: require("../../../assets/profiles/people/in-m-09.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-09.jpg"),
  },
  "in-m-10": {
    hd: require("../../../assets/profiles/people/in-m-10.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-10.jpg"),
  },
  "in-m-11": {
    hd: require("../../../assets/profiles/people/in-m-11.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-11.jpg"),
  },
  "in-m-12": {
    hd: require("../../../assets/profiles/people/in-m-12.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-12.jpg"),
  },
  "in-m-13": {
    hd: require("../../../assets/profiles/people/in-m-13.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-13.jpg"),
  },
  "in-m-14": {
    hd: require("../../../assets/profiles/people/in-m-14.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-14.jpg"),
  },
  "in-m-15": {
    hd: require("../../../assets/profiles/people/in-m-15.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-15.jpg"),
  },
  "in-m-16": {
    hd: require("../../../assets/profiles/people/in-m-16.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-16.jpg"),
  },
  "in-m-17": {
    hd: require("../../../assets/profiles/people/in-m-17.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-17.jpg"),
  },
  "in-m-18": {
    hd: require("../../../assets/profiles/people/in-m-18.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-18.jpg"),
  },
  "in-m-19": {
    hd: require("../../../assets/profiles/people/in-m-19.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-19.jpg"),
  },
  "in-m-20": {
    hd: require("../../../assets/profiles/people/in-m-20.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-20.jpg"),
  },
  "in-m-21": {
    hd: require("../../../assets/profiles/people/in-m-21.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-21.jpg"),
  },
  "in-m-22": {
    hd: require("../../../assets/profiles/people/in-m-22.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-22.jpg"),
  },
  "in-m-23": {
    hd: require("../../../assets/profiles/people/in-m-23.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-23.jpg"),
  },
  "in-m-24": {
    hd: require("../../../assets/profiles/people/in-m-24.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-m-24.jpg"),
  },
  "in-w-01": {
    hd: require("../../../assets/profiles/people/in-w-01.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-01.jpg"),
  },
  "in-w-02": {
    hd: require("../../../assets/profiles/people/in-w-02.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-02.jpg"),
  },
  "in-w-03": {
    hd: require("../../../assets/profiles/people/in-w-03.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-03.jpg"),
  },
  "in-w-04": {
    hd: require("../../../assets/profiles/people/in-w-04.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-04.jpg"),
  },
  "in-w-05": {
    hd: require("../../../assets/profiles/people/in-w-05.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-05.jpg"),
  },
  "in-w-06": {
    hd: require("../../../assets/profiles/people/in-w-06.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-06.jpg"),
  },
  "in-w-07": {
    hd: require("../../../assets/profiles/people/in-w-07.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-07.jpg"),
  },
  "in-w-08": {
    hd: require("../../../assets/profiles/people/in-w-08.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-08.jpg"),
  },
  "in-w-09": {
    hd: require("../../../assets/profiles/people/in-w-09.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-09.jpg"),
  },
  "in-w-10": {
    hd: require("../../../assets/profiles/people/in-w-10.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-10.jpg"),
  },
  "in-w-11": {
    hd: require("../../../assets/profiles/people/in-w-11.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-11.jpg"),
  },
  "in-w-12": {
    hd: require("../../../assets/profiles/people/in-w-12.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-12.jpg"),
  },
  "in-w-13": {
    hd: require("../../../assets/profiles/people/in-w-13.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-13.jpg"),
  },
  "in-w-14": {
    hd: require("../../../assets/profiles/people/in-w-14.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-14.jpg"),
  },
  "in-w-15": {
    hd: require("../../../assets/profiles/people/in-w-15.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-15.jpg"),
  },
  "in-w-16": {
    hd: require("../../../assets/profiles/people/in-w-16.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-16.jpg"),
  },
  "in-w-17": {
    hd: require("../../../assets/profiles/people/in-w-17.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-17.jpg"),
  },
  "in-w-18": {
    hd: require("../../../assets/profiles/people/in-w-18.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-18.jpg"),
  },
  "in-w-19": {
    hd: require("../../../assets/profiles/people/in-w-19.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-19.jpg"),
  },
  "in-w-20": {
    hd: require("../../../assets/profiles/people/in-w-20.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-20.jpg"),
  },
  "in-w-21": {
    hd: require("../../../assets/profiles/people/in-w-21.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-21.jpg"),
  },
  "in-w-22": {
    hd: require("../../../assets/profiles/people/in-w-22.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-22.jpg"),
  },
  "in-w-23": {
    hd: require("../../../assets/profiles/people/in-w-23.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-23.jpg"),
  },
  "in-w-24": {
    hd: require("../../../assets/profiles/people/in-w-24.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/in-w-24.jpg"),
  },
  "sa-m-01": {
    hd: require("../../../assets/profiles/people/sa-m-01.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-01.jpg"),
  },
  "sa-m-02": {
    hd: require("../../../assets/profiles/people/sa-m-02.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-02.jpg"),
  },
  "sa-m-03": {
    hd: require("../../../assets/profiles/people/sa-m-03.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-03.jpg"),
  },
  "sa-m-04": {
    hd: require("../../../assets/profiles/people/sa-m-04.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-04.jpg"),
  },
  "sa-m-05": {
    hd: require("../../../assets/profiles/people/sa-m-05.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-05.jpg"),
  },
  "sa-m-06": {
    hd: require("../../../assets/profiles/people/sa-m-06.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-06.jpg"),
  },
  "sa-m-07": {
    hd: require("../../../assets/profiles/people/sa-m-07.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-07.jpg"),
  },
  "sa-m-08": {
    hd: require("../../../assets/profiles/people/sa-m-08.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-08.jpg"),
  },
  "sa-m-09": {
    hd: require("../../../assets/profiles/people/sa-m-09.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-09.jpg"),
  },
  "sa-m-10": {
    hd: require("../../../assets/profiles/people/sa-m-10.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-10.jpg"),
  },
  "sa-m-11": {
    hd: require("../../../assets/profiles/people/sa-m-11.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-11.jpg"),
  },
  "sa-m-12": {
    hd: require("../../../assets/profiles/people/sa-m-12.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-12.jpg"),
  },
  "sa-m-13": {
    hd: require("../../../assets/profiles/people/sa-m-13.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-13.jpg"),
  },
  "sa-m-14": {
    hd: require("../../../assets/profiles/people/sa-m-14.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-14.jpg"),
  },
  "sa-m-15": {
    hd: require("../../../assets/profiles/people/sa-m-15.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-15.jpg"),
  },
  "sa-m-16": {
    hd: require("../../../assets/profiles/people/sa-m-16.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-16.jpg"),
  },
  "sa-m-17": {
    hd: require("../../../assets/profiles/people/sa-m-17.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-17.jpg"),
  },
  "sa-m-18": {
    hd: require("../../../assets/profiles/people/sa-m-18.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-18.jpg"),
  },
  "sa-m-19": {
    hd: require("../../../assets/profiles/people/sa-m-19.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-19.jpg"),
  },
  "sa-m-20": {
    hd: require("../../../assets/profiles/people/sa-m-20.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-20.jpg"),
  },
  "sa-m-21": {
    hd: require("../../../assets/profiles/people/sa-m-21.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-21.jpg"),
  },
  "sa-m-22": {
    hd: require("../../../assets/profiles/people/sa-m-22.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-22.jpg"),
  },
  "sa-m-23": {
    hd: require("../../../assets/profiles/people/sa-m-23.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-23.jpg"),
  },
  "sa-m-24": {
    hd: require("../../../assets/profiles/people/sa-m-24.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-24.jpg"),
  },
  "sa-m-25": {
    hd: require("../../../assets/profiles/people/sa-m-25.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-25.jpg"),
  },
  "sa-m-26": {
    hd: require("../../../assets/profiles/people/sa-m-26.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-26.jpg"),
  },
  "sa-m-27": {
    hd: require("../../../assets/profiles/people/sa-m-27.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-27.jpg"),
  },
  "sa-m-28": {
    hd: require("../../../assets/profiles/people/sa-m-28.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-28.jpg"),
  },
  "sa-m-29": {
    hd: require("../../../assets/profiles/people/sa-m-29.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-29.jpg"),
  },
  "sa-m-30": {
    hd: require("../../../assets/profiles/people/sa-m-30.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-30.jpg"),
  },
  "sa-m-31": {
    hd: require("../../../assets/profiles/people/sa-m-31.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-31.jpg"),
  },
  "sa-m-32": {
    hd: require("../../../assets/profiles/people/sa-m-32.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-32.jpg"),
  },
  "sa-m-33": {
    hd: require("../../../assets/profiles/people/sa-m-33.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-33.jpg"),
  },
  "sa-m-34": {
    hd: require("../../../assets/profiles/people/sa-m-34.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-34.jpg"),
  },
  "sa-m-35": {
    hd: require("../../../assets/profiles/people/sa-m-35.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-35.jpg"),
  },
  "sa-m-36": {
    hd: require("../../../assets/profiles/people/sa-m-36.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-36.jpg"),
  },
  "sa-m-37": {
    hd: require("../../../assets/profiles/people/sa-m-37.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-37.jpg"),
  },
  "sa-m-38": {
    hd: require("../../../assets/profiles/people/sa-m-38.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-38.jpg"),
  },
  "sa-m-39": {
    hd: require("../../../assets/profiles/people/sa-m-39.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-39.jpg"),
  },
  "sa-m-40": {
    hd: require("../../../assets/profiles/people/sa-m-40.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-40.jpg"),
  },
  "sa-m-41": {
    hd: require("../../../assets/profiles/people/sa-m-41.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-41.jpg"),
  },
  "sa-m-42": {
    hd: require("../../../assets/profiles/people/sa-m-42.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-42.jpg"),
  },
  "sa-m-43": {
    hd: require("../../../assets/profiles/people/sa-m-43.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-43.jpg"),
  },
  "sa-m-44": {
    hd: require("../../../assets/profiles/people/sa-m-44.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-44.jpg"),
  },
  "sa-m-45": {
    hd: require("../../../assets/profiles/people/sa-m-45.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-45.jpg"),
  },
  "sa-m-46": {
    hd: require("../../../assets/profiles/people/sa-m-46.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-46.jpg"),
  },
  "sa-m-47": {
    hd: require("../../../assets/profiles/people/sa-m-47.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-47.jpg"),
  },
  "sa-m-48": {
    hd: require("../../../assets/profiles/people/sa-m-48.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-m-48.jpg"),
  },
  "sa-w-01": {
    hd: require("../../../assets/profiles/people/sa-w-01.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-01.jpg"),
  },
  "sa-w-02": {
    hd: require("../../../assets/profiles/people/sa-w-02.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-02.jpg"),
  },
  "sa-w-03": {
    hd: require("../../../assets/profiles/people/sa-w-03.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-03.jpg"),
  },
  "sa-w-04": {
    hd: require("../../../assets/profiles/people/sa-w-04.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-04.jpg"),
  },
  "sa-w-05": {
    hd: require("../../../assets/profiles/people/sa-w-05.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-05.jpg"),
  },
  "sa-w-06": {
    hd: require("../../../assets/profiles/people/sa-w-06.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-06.jpg"),
  },
  "sa-w-07": {
    hd: require("../../../assets/profiles/people/sa-w-07.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-07.jpg"),
  },
  "sa-w-08": {
    hd: require("../../../assets/profiles/people/sa-w-08.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-08.jpg"),
  },
  "sa-w-09": {
    hd: require("../../../assets/profiles/people/sa-w-09.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-09.jpg"),
  },
  "sa-w-10": {
    hd: require("../../../assets/profiles/people/sa-w-10.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-10.jpg"),
  },
  "sa-w-11": {
    hd: require("../../../assets/profiles/people/sa-w-11.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-11.jpg"),
  },
  "sa-w-12": {
    hd: require("../../../assets/profiles/people/sa-w-12.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-12.jpg"),
  },
  "sa-w-13": {
    hd: require("../../../assets/profiles/people/sa-w-13.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-13.jpg"),
  },
  "sa-w-14": {
    hd: require("../../../assets/profiles/people/sa-w-14.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-14.jpg"),
  },
  "sa-w-15": {
    hd: require("../../../assets/profiles/people/sa-w-15.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-15.jpg"),
  },
  "sa-w-16": {
    hd: require("../../../assets/profiles/people/sa-w-16.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-16.jpg"),
  },
  "sa-w-17": {
    hd: require("../../../assets/profiles/people/sa-w-17.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-17.jpg"),
  },
  "sa-w-18": {
    hd: require("../../../assets/profiles/people/sa-w-18.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-18.jpg"),
  },
  "sa-w-19": {
    hd: require("../../../assets/profiles/people/sa-w-19.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-19.jpg"),
  },
  "sa-w-20": {
    hd: require("../../../assets/profiles/people/sa-w-20.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-20.jpg"),
  },
  "sa-w-21": {
    hd: require("../../../assets/profiles/people/sa-w-21.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-21.jpg"),
  },
  "sa-w-22": {
    hd: require("../../../assets/profiles/people/sa-w-22.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-22.jpg"),
  },
  "sa-w-23": {
    hd: require("../../../assets/profiles/people/sa-w-23.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-23.jpg"),
  },
  "sa-w-24": {
    hd: require("../../../assets/profiles/people/sa-w-24.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-24.jpg"),
  },
  "sa-w-25": {
    hd: require("../../../assets/profiles/people/sa-w-25.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-25.jpg"),
  },
  "sa-w-26": {
    hd: require("../../../assets/profiles/people/sa-w-26.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-26.jpg"),
  },
  "sa-w-27": {
    hd: require("../../../assets/profiles/people/sa-w-27.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-27.jpg"),
  },
  "sa-w-28": {
    hd: require("../../../assets/profiles/people/sa-w-28.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-28.jpg"),
  },
  "sa-w-29": {
    hd: require("../../../assets/profiles/people/sa-w-29.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-29.jpg"),
  },
  "sa-w-30": {
    hd: require("../../../assets/profiles/people/sa-w-30.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-30.jpg"),
  },
  "sa-w-31": {
    hd: require("../../../assets/profiles/people/sa-w-31.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-31.jpg"),
  },
  "sa-w-32": {
    hd: require("../../../assets/profiles/people/sa-w-32.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-32.jpg"),
  },
  "sa-w-33": {
    hd: require("../../../assets/profiles/people/sa-w-33.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-33.jpg"),
  },
  "sa-w-34": {
    hd: require("../../../assets/profiles/people/sa-w-34.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-34.jpg"),
  },
  "sa-w-35": {
    hd: require("../../../assets/profiles/people/sa-w-35.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-35.jpg"),
  },
  "sa-w-36": {
    hd: require("../../../assets/profiles/people/sa-w-36.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-36.jpg"),
  },
  "sa-w-37": {
    hd: require("../../../assets/profiles/people/sa-w-37.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-37.jpg"),
  },
  "sa-w-38": {
    hd: require("../../../assets/profiles/people/sa-w-38.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-38.jpg"),
  },
  "sa-w-39": {
    hd: require("../../../assets/profiles/people/sa-w-39.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-39.jpg"),
  },
  "sa-w-40": {
    hd: require("../../../assets/profiles/people/sa-w-40.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-40.jpg"),
  },
  "sa-w-41": {
    hd: require("../../../assets/profiles/people/sa-w-41.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-41.jpg"),
  },
  "sa-w-42": {
    hd: require("../../../assets/profiles/people/sa-w-42.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-42.jpg"),
  },
  "sa-w-43": {
    hd: require("../../../assets/profiles/people/sa-w-43.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-43.jpg"),
  },
  "sa-w-44": {
    hd: require("../../../assets/profiles/people/sa-w-44.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-44.jpg"),
  },
  "sa-w-45": {
    hd: require("../../../assets/profiles/people/sa-w-45.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-45.jpg"),
  },
  "sa-w-46": {
    hd: require("../../../assets/profiles/people/sa-w-46.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-46.jpg"),
  },
  "sa-w-47": {
    hd: require("../../../assets/profiles/people/sa-w-47.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-47.jpg"),
  },
  "sa-w-48": {
    hd: require("../../../assets/profiles/people/sa-w-48.jpg"),
    thumb: require("../../../assets/profiles/people/thumbs/sa-w-48.jpg"),
  },
};
