// Generated by scripts/prepare-demo-captures.cjs. Fictional demo stills.
// box = detected person [x, y, w, h] in percent of the 16:9 frame; the UI draws it.
export type DemoGender = "man" | "woman";
export interface DemoStill {
  id: string;
  gender: DemoGender;
  source: number;
  box: readonly [number, number, number, number];
}
export const demoStills: readonly DemoStill[] = [
  { id: "w1", gender: "woman", source: require("../../../../assets/media/still-w1.jpg"), box: [49, 55, 7, 34] },
  { id: "w2", gender: "woman", source: require("../../../../assets/media/still-w2.jpg"), box: [4, 41, 32, 58] },
  { id: "w3", gender: "woman", source: require("../../../../assets/media/still-w3.jpg"), box: [53, 48, 9.5, 51.5] },
  { id: "w4", gender: "woman", source: require("../../../../assets/media/still-w4.jpg"), box: [44.5, 46, 10, 53.5] },
  { id: "w5", gender: "woman", source: require("../../../../assets/media/still-w5.jpg"), box: [49.5, 37, 14.5, 62.5] },
  { id: "w6", gender: "woman", source: require("../../../../assets/media/still-w6.jpg"), box: [39.5, 31.5, 25.5, 68] },
  { id: "w7", gender: "woman", source: require("../../../../assets/media/still-w7.jpg"), box: [42, 44.5, 6.5, 29] },
  { id: "w8", gender: "woman", source: require("../../../../assets/media/still-w8.jpg"), box: [42.5, 49, 7.5, 33.5] },
  { id: "m1", gender: "man", source: require("../../../../assets/media/still-m1.jpg"), box: [26, 33.5, 6.5, 29.5] },
  { id: "m2", gender: "man", source: require("../../../../assets/media/still-m2.jpg"), box: [63.5, 40.5, 7.5, 33] },
  { id: "m3", gender: "man", source: require("../../../../assets/media/still-m3.jpg"), box: [32.5, 27.5, 10.5, 51] },
  { id: "m4", gender: "man", source: require("../../../../assets/media/still-m4.jpg"), box: [0.5, 27, 20.5, 72.5] },
  { id: "m5", gender: "man", source: require("../../../../assets/media/still-m5.jpg"), box: [76, 27, 23.5, 72.5] },
  { id: "m6", gender: "man", source: require("../../../../assets/media/still-m6.jpg"), box: [54, 24.5, 8.5, 26.5] },
  { id: "m7", gender: "man", source: require("../../../../assets/media/still-m7.jpg"), box: [63.5, 44.5, 6, 25.5] },
];
