// Which pooled portrait a demo person gets. Pure: no React Native imports, so node tests can load it.
import assignments from "./portraitAssignments.json";
import pool from "./portraitPool.json";
import samples from "../../domain/surveillance/samples.json";
import { parsePersonName, type PersonGender, type PersonLook } from "./personName";
import { fullName } from "../../domain/common/text";

/*
 * portraitAssignments.json is generated by scripts/assign-demo-portraits.cjs:
 * every person in the demo data has one portrait, and no page shows two
 * people with the same one. Names outside the demo data (people added during
 * a session, the signed-in user) have no photo until one is uploaded, so their
 * avatar shows initials.
 */
const assigned: Record<string, string | undefined> = assignments;
const groups = new Map<string, string[]>();
const known = new Set<string>();
for (const entry of pool as readonly { id: string; gender: string; look: string }[]) {
  const key = entry.gender + "/" + entry.look;
  groups.set(key, [...(groups.get(key) ?? []), entry.id]);
  known.add(entry.id);
}
for (const ids of groups.values()) ids.sort();

/** Pool ids for one group, sorted. */
export function portraitIds(gender: PersonGender, look: PersonLook): readonly string[] {
  return groups.get(gender + "/" + look) ?? [];
}

/** Pool id of a demo person's portrait ("Dr. Kavita Rao · E1001" → "sa-w-07"); undefined outside the demo data. */
export function portraitIdFor(name: string): string | undefined {
  const person = parsePersonName(name);
  if (!person?.gender) return undefined;
  const id = assigned[person.name];
  return id && known.has(id) ? id : undefined;
}

// Bundled dummy photos stand in for "a photo was provided": the surveillance
// samples' base64 images and the legacy assets/profiles/<uid>.jpg files.
const owners = new Map<string, string>();
const ownersByUid = new Map<string, string>();
for (const record of Object.values(samples).flat()) {
  const setup = record.setup as { uid: string; first_name: string; last_name: string; image?: string };
  const name = fullName(setup);
  ownersByUid.set(setup.uid.toLowerCase(), name);
  if (setup.image) owners.set(setup.image, name);
}
const legacyFile = /profiles(?:\/|\\|%2F)(e100[123]|v2001)(?:\.[0-9a-f]+)?\.jpe?g/i;

/** The sample person a bundled dummy photo belongs to; undefined for real (uploaded) photos. */
export function bundledPhotoOwner(image?: string): string | undefined {
  if (!image) return undefined;
  const owner = owners.get(image);
  if (owner !== undefined) return owner;
  const uid = legacyFile.exec(image)?.[1];
  return uid ? (ownersByUid.get(uid.toLowerCase()) ?? "") : undefined;
}

/** Largest drawn size (dp) that uses the 256×256 thumbnail rather than the 1080×1080 file. */
export const PORTRAIT_THUMB_MAX = 96;
export type PortraitChoice = { uri: string } | { id: string; file: "hd" | "thumb" };

/**
 * What to draw for a person: an uploaded photo URI wins; bundled dummy photos
 * and missing images resolve to a demo person's pool portrait (the dummy's
 * owner when no name is given). Undefined means show initials.
 */
export function portraitChoice(
  name: string,
  options?: { image?: string; size?: number },
): PortraitChoice | undefined {
  const image = options?.image;
  const owner = bundledPhotoOwner(image);
  if (image && owner === undefined) return { uri: image };
  const id = portraitIdFor(name?.trim() ? name : (owner ?? ""));
  if (!id) return undefined;
  return { id, file: (options?.size ?? Infinity) <= PORTRAIT_THUMB_MAX ? "thumb" : "hd" };
}
