// Which pooled portrait a demo person gets. Pure: no React Native imports, so node tests can load it.
import assignments from "./portraitAssignments.json";
import pool from "./portraitPool.json";
import samples from "../../domain/surveillance/samples.json";
import { parsePersonName, type PersonGender, type PersonLook } from "./personName";

/*
 * portraitAssignments.json is generated by scripts/assign-demo-portraits.cjs:
 * every person in the demo data has one portrait, and no page shows two
 * people with the same one. Names outside the demo data (people added during
 * a session) hash into their (gender, look) group of the pool.
 */
const assigned: Record<string, string | undefined> = assignments;
const groups = new Map<string, string[]>();
const known = new Set<string>();
for (const entry of pool as readonly { id: string; gender: string; look: string }[]) {
  const key = entry.gender + "/" + entry.look;
  groups.set(key, [...(groups.get(key) ?? []), entry.id].sort());
  known.add(entry.id);
}

/** Pool ids for one group, sorted. */
export function portraitIds(gender: PersonGender, look: PersonLook): readonly string[] {
  return groups.get(gender + "/" + look) ?? [];
}

function hash(text: string) {
  let h = 2166136261;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/** Pool id of a person's portrait ("Dr. Kavita Rao · E1001" → "sa-w-07"); undefined when the gender is unknown. */
export function portraitIdFor(name: string): string | undefined {
  const person = parsePersonName(name);
  if (!person?.gender) return undefined;
  const id = assigned[person.name];
  if (id && known.has(id)) return id;
  const ids = portraitIds(person.gender, person.look ?? "international");
  return ids.length ? ids[hash(person.name) % ids.length] : undefined;
}

// Bundled dummy photos stand in for "a photo was provided": the surveillance
// samples' base64 images and the legacy assets/profiles/<uid>.jpg files.
const owners = new Map<string, string>();
const ownersByUid = new Map<string, string>();
for (const record of Object.values(samples).flat()) {
  const setup = record.setup as { uid: string; first_name: string; last_name: string; image?: string };
  const name = [setup.first_name, setup.last_name].filter(Boolean).join(" ");
  ownersByUid.set(setup.uid.toLowerCase(), name);
  if (setup.image) owners.set(setup.image, name);
}
const legacyFile = /profiles(?:\/|\\|%2F)(e100[123]|v2001)(?:\.[0-9a-f]+)?\.jpe?g/i;

/** The sample person a bundled dummy photo belongs to; undefined for real (uploaded) photos. */
export function bundledPhotoOwner(image?: string): string | undefined {
  if (!image) return undefined;
  const owner = owners.get(image);
  if (owner !== undefined) return owner;
  const uid = legacyFile.exec(image)?.[1];
  return uid ? (ownersByUid.get(uid.toLowerCase()) ?? "") : undefined;
}

/** Largest drawn size (dp) that uses the 256×256 thumbnail rather than the 1080×1080 file. */
export const PORTRAIT_THUMB_MAX = 96;
export type PortraitChoice = { uri: string } | { id: string; file: "hd" | "thumb" };

/**
 * What to draw for a person: an uploaded photo URI wins; bundled dummy photos
 * and missing images resolve to the person's pool portrait (the dummy's owner
 * when no name is given). Undefined means show initials.
 */
export function portraitChoice(
  name: string,
  options?: { image?: string; size?: number },
): PortraitChoice | undefined {
  const image = options?.image;
  const owner = bundledPhotoOwner(image);
  if (image && owner === undefined) return { uri: image };
  const id = portraitIdFor(name?.trim() ? name : (owner ?? ""));
  if (!id) return undefined;
  return { id, file: (options?.size ?? Infinity) <= PORTRAIT_THUMB_MAX ? "thumb" : "hd" };
}
